[package]
name = "iced_starter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = {version = "0.10", features = ["image"]}
iced_native = "0.10"
env_logger = "0.10"
console_log = "1.0"
log = "0.4.20"
