[package]
name = "view_skater"
version = "0.1.2"
edition = "2021"
description = "A fast image viewer for browsing large collections of images."


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
env_logger = "0.10"
console_log = "1.0"
log = "0.4.20"
tokio = { version = "1.32", features = ["rt", "sync", "macros", "time", "io-util", "fs"] }
rfd = "0.12"
num-traits = "0.2"
alphanumeric-sort = "1.5.3"
image = "0.23"
futures = "0.3"
once_cell = "1.16"
smol_str = "0.2.2"
backtrace = "0.3"
dirs = "5.0"
lazy_static = "1.4"
webbrowser = "0.7"
bytemuck = { version = "1.0", features = ["derive"] }
iced_wgpu = "0.13.5"
wgpu = "23.0"
pollster = "0.4.0"

[target.'cfg(not(target_os = "linux"))'.dependencies]
iced_custom = { package = "iced", git = "https://github.com/ggand0/iced.git", rev = "69a425da03f227a8fd0e654eeb1e2d8c271e4411", features = [
        "image", "tokio", "svg", "lazy", "wgpu"]  }
iced_aw_custom = { package = "iced_aw", git = "https://github.com/ggand0/iced_aw.git", rev = "7897549ee9100b5095a9e934c3decdfbdbdc2818", features = [
    "menu", "quad" ] }

[target.'cfg(target_os = "linux")'.dependencies]
iced = {version = "0.13", features = ["image", "tokio", "svg", "lazy", "debug"]}
iced_aw = { version = "0.11.0", features = [
    "menu",
    "quad",
] }

[dev-dependencies]
cargo-bundle = "0.6.0"

[build-dependencies]
winres = "0.1.12"

[package.metadata.winres]
OriginalFilename = "view_skater.exe"
FileDescription = "A fast image viewer for browsing large collections of images."

[package.metadata.bundle]
name = "ViewSkater"
identifier = "com.ggando.viewskater"
icon = ["assets/icon_16.png", "assets/icon_32.png", "assets/icon_48.png", "assets/icon_128.png", "assets/icon_256.png"]
short_description = "A fast image viewer for browsing large collections of images."
