[package]
name = "view_skater"
version = "0.1.2"
edition = "2021"
description = "A fast image viewer for browsing large collections of images."


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
env_logger = "0.10"
console_log = "1.0"
log = "0.4.20"
tokio = { version = "1.32", features = ["rt", "sync", "macros", "time", "io-util", "fs"] }
rfd = "0.12"
num-traits = "0.2"
alphanumeric-sort = "1.5.3"
image = "0.23"
futures = "0.3"
once_cell = "1.16"
smol_str = "0.2.2"
backtrace = "0.3"
dirs = "5.0"
lazy_static = "1.4"
webbrowser = "0.7"
bytemuck = { version = "1.0", features = ["derive"] }
#iced_wgpu = "0.13.5"
wgpu = "23.0"
pollster = "0.4.0"
tracing-subscriber = "0.3"

[target.'cfg(not(target_os = "linux"))'.dependencies]
#iced_custom = { package = "iced", git = "https://github.com/ggand0/iced.git", rev = "ea76d7320e0967e2ec3d028d3d833c1d9ce53b58", features = [
#    "image", "tokio", "svg", "lazy", "wgpu"
#] }

#iced_aw_custom = { package = "iced_aw", git = "https://github.com/ggand0/iced_aw.git", rev = "7897549ee9100b5095a9e934c3decdfbdbdc2818", features = [
#iced_aw = { package = "iced_aw", git = "https://github.com/ggand0/iced_aw.git", rev = "a6008baadc357d116acb2b0caa8b14fed1bf717e", features = [
#    "menu", "quad" ] }
#iced_aw = { path = "../iced_aw", features = ["menu", "quad"] }


[target.'cfg(target_os = "linux")'.dependencies]
# debug setup with local iced
#iced_custom = { package = "iced", path = "../iced", features=["image", "tokio", "svg", "lazy", "wgpu", "advanced"] }
#iced_winit = { path = "../iced/winit" }
#iced_wgpu = { path = "../iced/wgpu" }
#iced_widget = { path = "../iced/widget", features = ["wgpu", "image"] }
#iced_core = { path = "../iced/core" }
#iced_runtime = { path = "../iced/runtime" }
#iced_futures = { path = "../iced/futures", features = ["tokio"] }
#iced_aw = { path = "../iced_aw", features = ["menu", "quad"] }

# v1 setup
iced_custom = { package = "iced", git = "https://github.com/ggand0/iced.git", rev = "ea76d7320e0967e2ec3d028d3d833c1d9ce53b58", features = [
    "image", "tokio", "svg", "lazy", "wgpu"
] }
iced_winit = { package = "iced_winit", git = "https://github.com/ggand0/iced.git", rev = "ea76d7320e0967e2ec3d028d3d833c1d9ce53b58" }
iced_wgpu = { package = "iced_wgpu", git = "https://github.com/ggand0/iced.git", rev = "ea76d7320e0967e2ec3d028d3d833c1d9ce53b58" }
iced_widget = { package = "iced_widget", git = "https://github.com/ggand0/iced.git", rev = "ea76d7320e0967e2ec3d028d3d833c1d9ce53b58", features = ["wgpu"] }
iced_core = { package = "iced_core", git = "https://github.com/ggand0/iced.git", rev = "ea76d7320e0967e2ec3d028d3d833c1d9ce53b58" }
iced_runtime = { package = "iced_runtime", git = "https://github.com/ggand0/iced.git", rev = "ea76d7320e0967e2ec3d028d3d833c1d9ce53b58" }
iced_futures = { package = "iced_futures", git = "https://github.com/ggand0/iced.git", rev = "ea76d7320e0967e2ec3d028d3d833c1d9ce53b58", features = ["tokio"] }
iced_aw = { package = "iced_aw", git = "https://github.com/ggand0/iced_aw.git", rev = "a6008baadc357d116acb2b0caa8b14fed1bf717e", features = [
    "menu", "quad" ] }


# v0 setup
#iced_winit = "0.13"
#iced_wgpu = "0.13.5"
#iced_widget = { version = "0.13", features = ["wgpu"] }
#iced_core = "0.13"
#iced_runtime = "0.13"
#iced_futures = { version = "0.13", features = ["tokio"] }
#iced = {version = "0.13", features = ["image", "tokio", "svg", "lazy", "debug"]}
#iced_aw = { version = "0.11.0", features = [
#    "menu",
#    "quad",
#] }


[dev-dependencies]
cargo-bundle = "0.6.0"

[build-dependencies]
winres = "0.1.12"

[package.metadata.winres]
OriginalFilename = "view_skater.exe"
FileDescription = "A fast image viewer for browsing large collections of images."

[package.metadata.bundle]
name = "ViewSkater"
identifier = "com.ggando.viewskater"
icon = ["assets/icon_16.png", "assets/icon_32.png", "assets/icon_48.png", "assets/icon_128.png", "assets/icon_256.png"]
short_description = "A fast image viewer for browsing large collections of images."
